[package]
name    = "vectorcalc"
version = "0.1.4"
entry   = "src/lib.vani"
authors = "enthusiasticgeek"
license = "MIT"
registry = "kosh"

[deps]
calculus = { path = "./vendor/calculus", version = "^0.2.0" }
